core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
        path('', views.index, name='index'),
        path('contact/', views.contact, name='contact'),
        path('signup/', views.signup, name='signup'),
        path('new/', views.new, name='new'),
        path('login/', auth_views.LoginView.as_view(
            authentication_form=LoginForm,
            template_name='core/login.html'
            ), name='login')
    ]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import detail
# from core import views.index

# app_name = 'item' # create namespace

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/<int:pk>/', detail, name='detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        ordering = ('title', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()

    image = models.ImageField(upload_to='item_images', blank=True, null=True)    
    is_sold = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class StrategyCard(models.Model):
    title = models.CharField(max_length=200)
    # is_fulfilled = models.BooleanField(default=False)
    def __str__(self):
        return self.title

class StrategyDeck(models.Model):
    title = models.CharField(max_length=200)
    strategies = models.ManyToManyField(StrategyCard, related_name='deck_strategies', blank=True)
    def __str__(self):
        return self.title
    
class Note(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=2000)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Transaction(models.Model):
    # transaction_series = models.ForeignKey(Series, on_delete=models.SET_NULL, null=True)
    ACTION_CHOICES = (('buy', 'buy'),
                    ('sell', 'sell'))

    actionType = models.CharField(choices=ACTION_CHOICES, max_length=200, default='buy')
    fulfilled_strategies = models.ManyToManyField(StrategyCard, related_name='fulfilled_series', blank=True)
    annotation = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)




    class Meta:
        pass
        # ordering = ['-updated', '-created', 'like_count', 'message_count']
    def __str__(self):
        return self.annotation


class TransactionSeries(models.Model):
# investor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
# adopted_deck = models.ForeignKey(StrategyDeck, on_delete=models.PROTECT, null=True)
    title = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True)

    adoptedStrategyCard = models.ManyToManyField(StrategyCard, related_name='strategy_series', blank=True)
    adoptedStrategyDeck = models.ManyToManyField(StrategyDeck, related_name='strategy_series', blank=True)
    
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title
    

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=('category', 'name', 'description', 'price', 'image')
        widgets = {
                'category': forms.Select(attrs={
                        'class': INPUT_CLASSES
                    }),
                'name': forms.TextInput(attrs={
                        'class': INPUT_CLASSES
                    }),
                'description': forms.Textarea(attrs={
                        'class': INPUT_CLASSES
                    }),
                'price': forms.TextInput(attrs={
                        'class': INPUT_CLASSES
                    }),
                'image': forms.FileInput(attrs={
                        'class': INPUT_CLASSES
                    }),
            }

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    password = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class': 'w-full py-4 px-6 rounded-xl',
        }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Your email',
            'class': 'w-full py-4 px-6 rounded-xl',
        }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'your password',
            'class': 'w-full py-4 px-6 rounded-xl',
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'confirm password',
            'class': 'w-full py-4 px-6 rounded-xl',
        }))
    

core/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from .models import Category, Item

from .forms import SignupForm, NewItemForm

from django.contrib.auth.decorators import login_required

def index(request):
    context = {}
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()


    context = {
        'categories': categories,
        'items': items
        }
    return render(request, 'core/index.html', context)

def contact(request):
    context = {}
    return render(request, 'core/contact.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
        

    return render(request, 'core/signup.html', {
            'form': form
        })

def detail(request, pk): # card details
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)
    # print(related_items)


    context = {'item': item,
               'related_items': related_items}
    return render(request, 'core/detail.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        form=NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.creator = request.user
            item.save()

            return redirect('detail', pk=item.id)
    else:
        form = NewItemForm()

    form = NewItemForm()

    context = {'form': form,
               'title': 'New Item' }
    return render(request,
                  'core/newItemForm.html',
                  context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>
        {% block title %}
        {% endblock %}
        | Puddle
    </title>
</head>
<body>
    <nav class='px-6 py-6 flex justify-between items-center border-b border-gray-200'>
        <a href='/' class='text-xl font-semibold'>Puddle</a>

        <div class='space-x-6'>
            <a href='{% url "core:new" %}' class='text-lg font-semibold hover:text-gray-500'>New Item</a>
            <a href='#' class='text-lg font-semibold hover:text-gray-500'>Browse</a>
            
            {% if not request.user.is_authenticated %}
            <a href='{% url "core:signup" %}' class='px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700'>Sign up</a>
            <a href='{% url "core:login" %}' class='px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700'>Log in</a>
            {% else %}
            <a href='#' class='px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700'>Inbox</a>
            <a href='#' class='px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700'>Dashboard</a>
            <a href='#' class='px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700'>Log out</a>
            {% endif %}
        </div>
    </nav>

    <div class='px-6 py-6'>
        {% block content %}
        {% endblock %}
    </div>

    <footer class='px-6 py-6 flex justify-between bg-gray-800'>
        <div class='w-2/3 pr-10'>
            <h3 class='mb-5 font-semibold text-gray-400'>About</h3>
            
            <p class='text-lg text-gray-500'>afdadsf asdfadsf asdfsadf asdfasd asdf</p>
        </div>
        
        <div class='w-1/3'>
            <h3 class='mb-5 font-semibold text-gray-400'>Menu</h3>
            <u1 class='space-y-2 list-none'>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>About</a></li>
                <li><a href='{% url "core:contact" %}' class='text-lg text-teal-500 hover:text-teal-700'>Contact</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Privacy</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Terms of Use</a></li>
            </u1>
            
        </div>
    </footer>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
Contact
{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/detail.html
{% extends 'core/base.html' %}

{% block title %}
{{item.name}}
{% endblock %}

{% block content %}
<div class='grid grid-cols-5 gap-6'>
    <div class='col-span-3'>
        <img src='{{item.image.url}}' class='rounded-xl'>
    </div>

    <div class='col-span-2 p-6 bg-gray-100 rounded-xl'>
        <h1 class='mb-6 text-3xl'>{{item.name}}</h1>
        <p class='text-gray-500'><strong>Price: </strong>{{item.price}}</p>
        <p class='text-gray-500'><strong>Seller: </strong>{{item.creator.username}}</p>

        {% if item.description %}
        <p class='text-gray-700'>
            <strong class='text-gray-500'>Description</strong><br>
            {{item.description}}
        </p>
        {% endif %}

        <a href='#'
            class='inline-block
            mt-6 px-6 py-3 text-lg
            font-semibold bg-teal-500
            text-white rounded-xl
            hover:bg-teal-700'>
            Contact Seller
        </a>
        
    </div>
</div>
<div class='mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h2 class='mb-12 text-2xl text-center'>Related Items</h2>

    <div class='grid grid-cols-3 gap-3'>
        {% for related_item in related_items %}

        <div>
            <a href='{% url "detail" related_item.id %}'>
                <div>
                    <img src='{{related_item.image.url }}' class='rounded-t-xl'>
                </div>
                
                <div class='p-6 bg-white rounded-b-xl'>
                    <h2 class='text-2xl'>{{related_item.title}}</h2>
                    <p class='text-gray-500'>Price: {{related_item.price}}</p>
                </div>
            </a>
        </div>
        
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
    <div class='mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center'>Newest Items</h2>

        <div class='grid grid-cols-3 gap-3'>
            {% for item in items %}

            <div>
                <a href='{% url "detail" item.id %}'>
                    <div>
                        <img src='{{item.image.url }}' class='rounded-t-xl'>
                    </div>
                    
                    <div class='p-6 bg-white rounded-b-xl'>
                        <h2 class='text-2xl'>{{item.title}}</h2>
                        <p class='text-gray-500'>Price: {{item.price}}</p>
                    </div>
                </a>
            </div>
            
            {% endfor %}
        </div>
    </div>

    <!-- Your Decks -->
    <div class='mt-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center'>Categories</h2>

        <div class='grid grid-cols-3 gap-3'>
            {% for category in categories %}
            <div>
                <a href='#'>

                    
                    <div class='p-6 bg-white rounded-b-xl'>
                        <h2 class='text-2xl'>{{category.title}}</h2>
                        <p class='text-gray-500'>{{category.items.count}} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<div class='w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl'>
    <h1 class='mb-6 text-3xl'>Log in</h1>

    <form method='post' action='.'>
        {% csrf_token %}

        <!-- {{form.as_p}} -->

        <div class='mb-3'>
            <label class='inline-block mb-2'>Username</label><br>
            {{form.username}}
        </div>

        <div class='mb-3'>
            <label class='inline-block mb-2'>Password</label><br>
            {{form.password}}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6 bg-red-100 rounded-xl'>
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{form.non_field_errors}}
            </div>
        {% endif %}

        <button class='py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>
            Submit
        </button>
    </form>
</div>
{% endblock %}

core/templates/core/newItemForm.html
{% extends 'core/base.html' %}

{% block title %}
{{title}}
{% endblock %}

{% block content %}
<h1 class='mb-6 text-3xl'>{{title}}</h1>

<form method='post' action='.' enctype='multipart/form-data'>
    {% csrf_token %}
    <div class='space-y-4'>
        {{form.as_p}}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div class='mb-3 p-6 bg-red-100 rounded-xl'>
            {% for field in form %}
                {{field.errors}}
            {% endfor %}

            {{form.non_field_errors}}
        </div>
    {% endif %}
    <button class='mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>
        Submit
    </button>
</form>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock %}

{% block content %}
<div class='w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl'>
    <h1 class='mb-6 text-3xl'>Sign up</h1>

    <form method='post' action='.'>
        {% csrf_token %}

        <!-- {{form.as_p}} -->

        <div class='mb-3'>
            <label class='inline-block mb-2'>Username</label><br>
            {{form.username}}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Email</label><br>
            {{form.email}}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Password</label><br>
            {{form.password1}}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6 bg-red-100 rounded-xl'>
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{form.non_field_errors}}
            </div>
        {% endif %}
        <div class='mb-3'>
            <label class='inline-block mb-2'>Confirm Password</label><br>
            {{form.password2}}
        </div>

        <button class='py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white'>
            Submit
        </button>
    </form>
</div>
{% endblock %}